/* AUTO-GENERATED by platform/build.py from data/exercises.json.
 * Do not edit this file directly — edit the JSON and re-run the build. */
window.AI4M_DATA = {
  "schema_version": "2.0",
  "generated_for": "A60 - AI4Mobility: A Multimodal Assistive Platform for Parents Supporting Children with Mobility Difficulties",
  "note": "Each programme stores the ORIGINAL source description verbatim in `original_description`. The `steps` array is the output of the step-splitting engine, reviewed by hand. Both are shown in the interface so a parent can compare them.",
  "programmes": [
    {
      "id": "childs-pose",
      "title": "Child's Pose",
      "also_called": "Balasana",
      "family": "Stretch and relax",
      "icon": "🐢",
      "colour": "aqua",
      "difficulty": 1,
      "duration_min": 2,
      "why_kids_like_it": "You get to curl up like a sleepy turtle hiding in its shell.",
      "goal": "Gently lengthens the lower back and hips and gives a calm resting position between harder exercises.",
      "source_name": "Common therapeutic resting posture; described in paediatric and adult stretch programmes",
      "source_url": "",
      "evidence_label": "Described from standard practice — not copied from a single NHS leaflet",
      "original_description": "Kneel on the floor with your knees apart and your big toes touching. Sit back onto your heels, then fold forward and rest your tummy between your thighs. Stretch your arms out in front of you along the floor and let your forehead rest down. Breathe slowly and hold the position, then walk your hands back and sit up.",
      "safety": "Stop if there is knee or hip pain. A cushion under the hips or knees makes it easier.",
      "steps": [
        {
          "n": 1,
          "text": "Kneel on the floor with your knees apart and your big toes touching.",
          "hold_s": 0,
          "pose": "kneel",
          "cue": "Knees wide like a frog."
        },
        {
          "n": 2,
          "text": "Sit back onto your heels.",
          "hold_s": 0,
          "pose": "sit_heels",
          "cue": "Bottom down to your feet."
        },
        {
          "n": 3,
          "text": "Fold forward and rest your tummy between your thighs.",
          "hold_s": 0,
          "pose": "fold",
          "cue": "Curl up small like a turtle."
        },
        {
          "n": 4,
          "text": "Stretch your arms out in front of you along the floor and let your forehead rest down.",
          "hold_s": 0,
          "pose": "arms_long",
          "cue": "Long arms, sleepy head."
        },
        {
          "n": 5,
          "text": "Breathe slowly and hold the position.",
          "hold_s": 20,
          "pose": "arms_long",
          "cue": "Big slow breaths."
        },
        {
          "n": 6,
          "text": "Walk your hands back and sit up.",
          "hold_s": 0,
          "pose": "kneel",
          "cue": "Slowly wake up."
        }
      ]
    },
    {
      "id": "cat-cow",
      "title": "Cat–Cow Stretch",
      "also_called": "Marjaryasana–Bitilasana",
      "family": "Stretch and mobility",
      "icon": "🐱",
      "colour": "orange",
      "difficulty": 1,
      "duration_min": 3,
      "why_kids_like_it": "You get to be a grumpy cat and then a happy cow, over and over.",
      "goal": "Moves the spine through bending and arching to improve back mobility and body awareness.",
      "source_name": "Widely used paediatric mobility exercise; taught as a two-part flow",
      "source_url": "",
      "evidence_label": "Described from standard practice — not copied from a single NHS leaflet",
      "original_description": "Start on your hands and knees with your wrists under your shoulders and your knees under your hips. Breathe in and drop your tummy towards the floor, lifting your chest and looking gently forwards — this is Cow. Breathe out and round your back up towards the ceiling, tucking your chin towards your chest — this is Cat. Move slowly between the two positions and repeat ten times.",
      "safety": "Move slowly and only as far as is comfortable. Stop if there is neck or back pain.",
      "steps": [
        {
          "n": 1,
          "text": "Start on your hands and knees with your wrists under your shoulders and your knees under your hips.",
          "hold_s": 0,
          "pose": "table",
          "cue": "Strong table, flat back."
        },
        {
          "n": 2,
          "text": "Breathe in and drop your tummy towards the floor, lifting your chest and looking gently forwards.",
          "hold_s": 3,
          "pose": "cow",
          "cue": "Happy cow — tummy down."
        },
        {
          "n": 3,
          "text": "Breathe out and round your back up towards the ceiling, tucking your chin towards your chest.",
          "hold_s": 3,
          "pose": "cat",
          "cue": "Grumpy cat — back up high."
        },
        {
          "n": 4,
          "text": "Move slowly between the two positions and repeat ten times.",
          "hold_s": 0,
          "reps": 10,
          "pose": "flow",
          "cue": "Cow … cat … cow … cat."
        }
      ]
    },
    {
      "id": "thread-the-needle",
      "title": "Thread the Needle",
      "also_called": "Parsva Balasana",
      "family": "Stretch and mobility",
      "icon": "🧵",
      "colour": "magenta",
      "difficulty": 2,
      "duration_min": 3,
      "why_kids_like_it": "Your arm sneaks through a gap like thread going through a needle.",
      "goal": "Stretches the shoulders, arms, upper back and neck, and adds a gentle rotation to the upper spine.",
      "source_name": "Yoga Basics — Threading the Needle",
      "source_url": "https://www.yogabasics.com/asana/threading-the-needle/",
      "evidence_label": "Instructions adapted from the cited source",
      "original_description": "Start in Table pose on hands and knees, then slide the right hand between the left hand and left knee. Slide the arm all the way out to the left so that the right shoulder and side of the head rest comfortably on the floor. Inhale and reach the left hand up towards the ceiling. Breathe and hold for 3 to 6 breaths. Release by exhaling your palm back down and slowly inhaling to return to Table pose. Repeat on the opposite side.",
      "safety": "Avoid if there is recent or chronic injury to the knees, shoulders or neck. A folded blanket under the knees protects them from pressure.",
      "steps": [
        {
          "n": 1,
          "text": "Start in Table pose on hands and knees.",
          "hold_s": 0,
          "pose": "table",
          "cue": "Strong table again."
        },
        {
          "n": 2,
          "text": "Slide the right hand between the left hand and left knee.",
          "hold_s": 0,
          "pose": "thread_start",
          "cue": "Sneak your hand through the gap."
        },
        {
          "n": 3,
          "text": "Slide the arm all the way out to the left so that the right shoulder and side of the head rest comfortably on the floor.",
          "hold_s": 0,
          "pose": "thread",
          "cue": "Rest your cheek on the floor."
        },
        {
          "n": 4,
          "text": "Inhale and reach the left hand up towards the ceiling.",
          "hold_s": 0,
          "pose": "thread_reach",
          "cue": "Point at the sky."
        },
        {
          "n": 5,
          "text": "Breathe and hold for 3 to 6 breaths.",
          "hold_s": 20,
          "pose": "thread_reach",
          "cue": "Count your breaths."
        },
        {
          "n": 6,
          "text": "Exhale your palm back down and slowly inhale to return to Table pose.",
          "hold_s": 0,
          "pose": "table",
          "cue": "Come back up."
        },
        {
          "n": 7,
          "text": "Repeat on the opposite side.",
          "hold_s": 0,
          "pose": "thread_mirror",
          "cue": "Now the other arm."
        }
      ]
    },
    {
      "id": "nhs-lower-limb",
      "title": "Lower Limb Exercises",
      "also_called": "NHS general lower limb guide",
      "family": "Strength — legs",
      "icon": "🦵",
      "colour": "blue",
      "difficulty": 2,
      "duration_min": 10,
      "why_kids_like_it": "Six quick leg missions you can do lying down.",
      "goal": "General lower limb range of movement and strengthening, done lying down so it is accessible from bed.",
      "source_name": "Sheffield Children's NHS Foundation Trust — General lower limb exercises",
      "source_url": "https://library.sheffieldchildrens.nhs.uk/general-lower-limb-exercises/",
      "evidence_label": "Instructions adapted from the cited NHS source",
      "original_description": "Ankle flexion: lay on your back with your leg straight. Point your foot and toes down to the floor or bed, then slowly pull your foot and toes up towards your knee. Repeat 10 times. Quadriceps contraction: lay on your back with your legs outstretched and your foot and toes pointing upward. Push your knee down firmly against the bed and hold for 5 seconds. Repeat 10 times. Glute squeeze: lay on your back with legs outstretched. Squeeze your bottom firmly together, hold for 5 seconds then relax. Repeat 10 times. Knee bending: lay on your back or sit. Bend your knee by bringing your heel towards your bottom, then return to the starting position. Repeat 10 times. Hip abduction: lay on your back with your legs together. Keeping your leg straight, bring your leg out to the side and return to the starting position. Make sure that you keep your knee and foot in line and your toes pointing upwards. Repeat 10 times. Prone lying: lay on your tummy with your head and arms positioned comfortably. Make sure your hips are level and in contact with the bed. Lie for 30 minutes.",
      "safety": "These are general exercises. Follow the specific programme given by your own physiotherapist. Stop and seek advice if pain gets worse.",
      "steps": [
        {
          "n": 1,
          "text": "Ankle flexion: lay on your back with your leg straight. Point your foot and toes down to the floor or bed, then slowly pull your foot and toes up towards your knee.",
          "hold_s": 0,
          "reps": 10,
          "pose": "supine_ankle",
          "cue": "Point … and pull up."
        },
        {
          "n": 2,
          "text": "Quadriceps contraction: with your legs outstretched and toes pointing upward, push your knee down firmly against the bed.",
          "hold_s": 5,
          "reps": 10,
          "pose": "supine_quad",
          "cue": "Squash the bed with your knee."
        },
        {
          "n": 3,
          "text": "Glute squeeze: lay on your back with legs outstretched and squeeze your bottom firmly together, then relax.",
          "hold_s": 5,
          "reps": 10,
          "pose": "supine_glute",
          "cue": "Squeeze … and let go."
        },
        {
          "n": 4,
          "text": "Knee bending: lay on your back or sit, then bend your knee by bringing your heel towards your bottom and return to the start.",
          "hold_s": 0,
          "reps": 10,
          "pose": "knee_bend",
          "cue": "Heel to your bottom."
        },
        {
          "n": 5,
          "text": "Hip abduction: lay on your back with legs together. Keeping your leg straight, bring your leg out to the side and return. Keep your knee and foot in line and your toes pointing upwards.",
          "hold_s": 0,
          "reps": 10,
          "pose": "hip_abduct",
          "cue": "Slide your leg out sideways."
        },
        {
          "n": 6,
          "text": "Prone lying: lay on your tummy with your head and arms comfortable and your hips level and in contact with the bed.",
          "hold_s": 1800,
          "pose": "prone",
          "cue": "Rest on your tummy."
        }
      ]
    },
    {
      "id": "paediatric-core-hip",
      "title": "Paediatric Physiotherapy Exercises",
      "also_called": "Core and hip stability",
      "family": "Strength — core and hips",
      "icon": "💪",
      "colour": "green",
      "difficulty": 3,
      "duration_min": 12,
      "why_kids_like_it": "Seven strength challenges, including one called the Dead Bug.",
      "goal": "Builds core and hip stability, which supports balance, walking and the harder movements in the other programmes.",
      "source_name": "Sheffield Children's NHS Foundation Trust — Core and hip stability exercises",
      "source_url": "https://library.sheffieldchildrens.nhs.uk/core-and-hip-stability-exercises/",
      "evidence_label": "Instructions adapted from the cited NHS source",
      "original_description": "All exercises should be performed 10 times, 3 to 4 times daily throughout the day, and all movements should be slow and smooth. Hip clams: lie on your side with the affected side on top, bend both legs and keep your pelvis level. Slowly lift your top knee away from the bottom knee, keeping feet and ankles together, then lower back down. Bridging: lie on your back with knees bent and feet apart and firmly on the surface. Squeeze your buttocks together and push through your heels, raising your bottom until your hips line up with your knees. Hold for 5 seconds. Four point kneeling: on hands and knees with wrists below shoulders and knees below hips, pull your stomach up and in, then extend one leg straight behind and hold for 5 seconds. Repeat on the opposite leg. One leg stands: stand upright on the affected leg using support if needed, keep your pelvis level and hold for 5 to 10 seconds. Hip hitching: standing upright, keep your pelvis level, lift your hip towards your shoulder and hold for 5 seconds. Dead bug: lie on your back with arms extended straight above and legs bent at right angles, then extend one arm overhead while lowering the opposite leg and return. Four point hip extension: lie on your stomach, bend the affected knee to a right angle and slowly raise your foot towards the ceiling, holding for 5 seconds.",
      "safety": "If pain becomes worse, stop the exercises and seek advice from a healthcare professional. Only perform the movements prescribed for your current stage.",
      "steps": [
        {
          "n": 1,
          "text": "Hip clams: lie on your side with both legs bent and your pelvis level. Slowly lift your top knee away from the bottom knee, keeping feet and ankles together, then lower back down.",
          "hold_s": 0,
          "reps": 10,
          "pose": "clam",
          "cue": "Open like a clam shell."
        },
        {
          "n": 2,
          "text": "Bridging: lie on your back with knees bent and feet firmly down. Squeeze your buttocks and push through your heels, raising your bottom until your hips line up with your knees.",
          "hold_s": 5,
          "reps": 10,
          "pose": "bridge",
          "cue": "Build a bridge with your hips."
        },
        {
          "n": 3,
          "text": "Four point kneeling: on hands and knees, pull your stomach up and in, then extend one leg straight behind you. Repeat on the opposite leg.",
          "hold_s": 5,
          "reps": 10,
          "pose": "quadruped_leg",
          "cue": "Long leg like a plane wing."
        },
        {
          "n": 4,
          "text": "One leg stands: stand upright on one leg, using support if needed, and keep your pelvis level.",
          "hold_s": 10,
          "reps": 10,
          "pose": "one_leg",
          "cue": "Stand tall like a flamingo."
        },
        {
          "n": 5,
          "text": "Hip hitching: standing upright with your pelvis level, lift your hip towards your shoulder.",
          "hold_s": 5,
          "reps": 10,
          "pose": "hip_hitch",
          "cue": "Shrug with your hip."
        },
        {
          "n": 6,
          "text": "Dead bug: lie on your back with arms straight above and legs bent at right angles. Extend one arm overhead while lowering the opposite leg, then return.",
          "hold_s": 0,
          "reps": 10,
          "pose": "dead_bug",
          "cue": "Wiggle like an upside-down bug."
        },
        {
          "n": 7,
          "text": "Four point hip extension: lie on your stomach, bend your knee to a right angle and slowly raise your foot towards the ceiling.",
          "hold_s": 5,
          "reps": 10,
          "pose": "prone_hip_ext",
          "cue": "Press your foot at the ceiling."
        }
      ]
    },
    {
      "id": "calf-control",
      "title": "Calf Control",
      "also_called": "Heel raises and calf work",
      "family": "Strength — legs",
      "icon": "🦶",
      "colour": "yellow",
      "difficulty": 2,
      "duration_min": 6,
      "why_kids_like_it": "Bonus level — tiptoe like you are sneaking up on someone.",
      "goal": "Builds calf strength and control, which supports walking, stair climbing and balance.",
      "source_name": "Sheffield Children's NHS Foundation Trust — Calf control exercises",
      "source_url": "https://library.sheffieldchildrens.nhs.uk/calf-control-exercises/",
      "evidence_label": "Optional extra programme — title and source verified, step wording written by the team and NOT copied from the leaflet",
      "optional": true,
      "original_description": "Stand upright holding a support such as a worktop. Rise up onto your toes slowly and with control, then lower your heels back to the floor slowly. Keep your ankles in line and do not let them roll outwards. Progress by using less support and then by working one leg at a time.",
      "safety": "This is an optional extra added by the team. Always use a support until balance is confident. Confirm with your physiotherapist before adding it.",
      "steps": [
        {
          "n": 1,
          "text": "Stand upright holding a support such as a worktop.",
          "hold_s": 0,
          "pose": "stand",
          "cue": "Hold on tight."
        },
        {
          "n": 2,
          "text": "Rise up onto your toes slowly and with control.",
          "hold_s": 3,
          "reps": 10,
          "pose": "heel_raise",
          "cue": "Sneaky tiptoes."
        },
        {
          "n": 3,
          "text": "Lower your heels back to the floor slowly.",
          "hold_s": 0,
          "reps": 10,
          "pose": "stand",
          "cue": "Down like a slow lift."
        },
        {
          "n": 4,
          "text": "Keep your ankles in line and do not let them roll outwards.",
          "hold_s": 0,
          "pose": "stand",
          "cue": "Straight ankles."
        }
      ]
    }
  ]
};
