#!/usr/bin/env python3
"""
Build script for the AI4Mobility platform.

Two jobs:
  1. Generate platform/js/data.js from data/exercises.json, so the single source
     of truth for exercise content is the JSON file.
  2. Inline every CSS and JS file into one self-contained HTML document at
     dist/ai4mobility.html, which opens from the filesystem with no server.

Usage:
    python3 platform/build.py
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLATFORM = ROOT / "platform"
DIST = ROOT / "dist"


def generate_data_js() -> int:
    """Write platform/js/data.js from data/exercises.json."""
    src = ROOT / "data" / "exercises.json"
    data = json.loads(src.read_text(encoding="utf-8"))

    payload = json.dumps(data, indent=2, ensure_ascii=False)
    out = (
        "/* AUTO-GENERATED by platform/build.py from data/exercises.json.\n"
        " * Do not edit this file directly — edit the JSON and re-run the build. */\n"
        "window.AI4M_DATA = " + payload + ";\n"
    )
    dest = PLATFORM / "js" / "data.js"
    dest.write_text(out, encoding="utf-8")
    n = len(data.get("programmes", []))
    print(f"  data.js        {n} programmes, {len(out) // 1024} KB")
    return n


def inline() -> Path:
    """Inline all local css/js into one HTML file."""
    html = (PLATFORM / "index.html").read_text(encoding="utf-8")

    def css_repl(match: re.Match) -> str:
        href = match.group(1)
        path = PLATFORM / href
        if not path.exists():
            print(f"  WARNING: missing stylesheet {href}", file=sys.stderr)
            return match.group(0)
        return "<style>\n" + path.read_text(encoding="utf-8") + "\n</style>"

    def js_repl(match: re.Match) -> str:
        src = match.group(1)
        path = PLATFORM / src
        if not path.exists():
            print(f"  WARNING: missing script {src}", file=sys.stderr)
            return match.group(0)
        return "<script>\n" + path.read_text(encoding="utf-8") + "\n</script>"

    html = re.sub(r'<link[^>]+href="([^"]+\.css)"[^>]*>', css_repl, html)
    html = re.sub(r'<script src="([^"]+\.js)"></script>', js_repl, html)

    # Guard: nothing local should remain unresolved.
    leftovers = [
        ref for ref in re.findall(r'(?:src|href)="(?!https?:|#|mailto:)([^"]+)"', html)
        # Ignore template literals inside the inlined JS (e.g. "${esc(p.source_url)}").
        if "${" not in ref and "{" not in ref
    ]
    if leftovers:
        print(f"  WARNING: unresolved local references: {leftovers}", file=sys.stderr)

    DIST.mkdir(exist_ok=True)
    dest = DIST / "ai4mobility.html"
    dest.write_text(html, encoding="utf-8")
    print(f"  ai4mobility.html  {len(html) // 1024} KB  ->  {dest.relative_to(ROOT)}")
    return dest


def main() -> int:
    print("Building AI4Mobility platform")
    generate_data_js()
    inline()
    print("Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
